services:
  hugo:
    image: hugomods/hugo:debian-nightly-non-root
    working_dir: /MyWebsite
    volumes:
      - .:/MyWebsite
    ports:
      - "1313:1313"
    command: >
      sh -c "hugo mod get -u &&
             hugo mod tidy &&
             hugo server --bind 0.0.0.0 --port 1313"
